apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url-deployment
spec:
  replicas: 3 # We'll get three identical pods
  selector:
    matchLabels:
      app: short-url-pod
  template:
    metadata:
      labels:
        app: short-url-pod
    spec:
      containers:
      - name: short-url-container
        image: pichayean/short-url:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: "Site__SiteId"
          value: "1"
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        ports:
        - containerPort: 5005
