# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  short-url:
    image: short-url
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./Databases/ShortURL.db:/app/ShortURL.db
    ports:
      - 5005:80
