apiVersion: v1
kind: Service
metadata:
  name: short-url-service
spec:
  selector:
    app: short-url-pod
  ports:
  - port: 5005
    targetPort: 80
  type: LoadBalancer
  externalIPs:
  - 194.233.73.42
  
