name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password --password-stdin
  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pichayean/short-url:$(date +%s)
      
    - name: Push image to Docker Hub
      run: docker push pichayean/short-url:$(date +%s)
      
